import Head from "next/head";
import React from "react";
import LandingPage from "./landing";

const index = () => {
  return (
    <div>
      <Head>
        <title>FlickerJoy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <LandingPage />
    </div>
  );
};

export default index;
