import useLogout from "@/hooks/useLogout";
import Head from "next/head";
import React from "react";

const LandingPage = () => {
  const { handleLogout } = useLogout();
  return (
    <div>
      <Head>
        <title>FlickerJoy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1>test</h1>
    </div>
  );
};

export default LandingPage;
